### ISSUE TITLE
Lontra-ui crashes when trying to harvest a second resource on the same session

### ISSUE THREAD

**Issue by tigreped** [WingLongitude/lontra-harvester#17]
That forces the users to close the UI and reopen a new ui for each resource. Stack trace example:

0 [SwingWorker-pool-2-thread-3] FATAL net.canadensys.harvester.occurrence.task.PrepareDwcaTask  - Conflicted DwcaFileLocation : http://ipt1.cria.org.br/ipt/archive.do?r=ase&v=1.6 and : /opt/harvest/ui/work/dwca-alcb-v1.6
0 [SwingWorker-pool-2-thread-3] FATAL net.canadensys.harvester.occurrence.task.PrepareDwcaTask  - Conflicted DwcaFileLocation : http://ipt1.cria.org.br/ipt/archive.do?r=ase&v=1.6 and : /opt/harvest/ui/work/dwca-alcb-v1.6
net.canadensys.harvester.exception.TaskExecutionException: Could not find the DarwinCore archive file null
	at net.canadensys.harvester.occurrence.task.PrepareDwcaTask.execute(PrepareDwcaTask.java:115)
	at net.canadensys.harvester.occurrence.job.ImportDwcaJob.doJob(ImportDwcaJob.java:80)
	at net.canadensys.harvester.occurrence.controller.StepController.importDwcA(StepController.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201)
	at com.sun.proxy.$Proxy39.importDwcA(Unknown Source)
	at net.canadensys.harvester.occurrence.view.ResourcesPanel$9.doInBackground(ResourcesPanel.java:403)
	at net.canadensys.harvester.occurrence.view.ResourcesPanel$9.doInBackground(ResourcesPanel.java:398)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cgendreau** [comment]
Yes, some objects are not immutable and are currently not reused properly.
